name: Build Image

on:
  push:
    tags:
      - "*.*.*"
  workflow_dispatch:

env:
  IMAGE_NAME: "loscienzo/linuxserver-io-mod-vuetorrent"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: DockerHub Login
        uses: docker/login-action@v1
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_PASSWORD}}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ IMAGE_NAME }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}, ${{ IMAGE_NAME }}:latest
          labels: ${{ steps.meta.outputs.labels }}
