#!/usr/bin/with-contenv bash

bash print-title-art # display title card

LATEST_RELEASE=$(curl -s -L https://api.github.com/repos/wdaan/vuetorrent/releases/latest \
              | grep "browser_download_url.*zip" \
              | cut -d : -f 2,3 \
              | tr -d \" \
              | xargs) # to trim whitespace

LATEST_RELEASE_VERSION=${LATEST_RELEASE%/*}
LATEST_RELEASE_VERSION=${LATEST_RELEASE_VERSION##*/}

download_vuetorrent () {
  curl -O -J -L $LATEST_RELEASE
}

extract_vuetorrent () {
  unzip vuetorrent.zip -d $1 | awk 'BEGIN {ORS=""} {if(NR%2==0)print "."} END{print "\n"}'
}

if [ ! -d /vuetorrent ]; then
  echo "Installing" $LATEST_RELEASE_VERSION"...\n"

  if download_vuetorrent; then
    extract_vuetorrent /

    rm /vuetorrent.zip # Remove zip after unpacking

    echo "Done! The theme is installed in the root folder. Apply it from WEBUI settings."
  fi
else
  echo "Installing" $LATEST_RELEASE_VERSION "using the alternate installer...\n"

  if download_vuetorrent; then
    extract_vuetorrent /temp-vuetorrent

    cp -r /temp-vuetorrent/vuetorrent/* /vuetorrent # mv throws error
    rm -r temp-vuetorrent

    rm vuetorrent.zip # Remove zip after unpacking

    echo "Done! The theme is installed in the root folder."
  fi
fi
