#!/usr/bin/with-contenv bash

cat installer-title-art

LATEST_RELEASE=$(curl -s -L https://api.github.com/repos/wdaan/vuetorrent/releases/latest \
              | grep "browser_download_url.*zip" \
              | cut -d : -f 2,3 \
              | tr -d \" \
              | xargs) # to trim whitespace

if [ ! -d /vuetorrent ]; then
  echo "Running installer..."

  curl -O -J -L $LATEST_RELEASE && unzip vuetorrent.zip -d /

  # Remove zip after unpacking
  rm /vuetorrent.zip

  echo "Done! The theme is installed in the root folder. Apply it from WEBUI settings."
else
  echo "Running alternate installer..."

  curl -O -J -L $LATEST_RELEASE && unzip vuetorrent.zip -d /temp-vuetorrent

  cp -r /temp-vuetorrent/vuetorrent/* /vuetorrent # mv throws error
  rm -r temp-vuetorrent

  rm vuetorrent.zip

  echo "Done! The theme is installed in the root folder."
fi
