#!/usr/bin/with-contenv bash

BLUE="\033[0;34m"
LIGHT_CYAN="\033[1;36m"
DARK_GRAY="\033[1;30m"

PC=$LIGHT_CYAN # Primary Color
SC=$BLUE # Secondary Color
NC="\033[0m" # No Color

# display title card
echo -e "-------------------------------------
${PC} _____ ${SC}        _____
${PC}|     |${SC}       //////
${PC}|     |${SC}      //////
${PC}|     |${SC}     //////
${PC}|     |${SC}    //////
${PC}|     |${SC}   //////
${PC}|     |${SC}  //////   _____       ${NC}The sleekest looking WebUI for qBittorrent made with Vue.js!
${PC}|     |${SC} //////   //////       ${DARK_GRAY}|  Vue, qBittorrent, Vuetify${NC}
${PC}|     |${SC}//////   //////
${PC}|     |${SC}/////   //////
${PC}|     |${SC}////${PC}   ____________${NC}
${PC}|     |${SC}///${PC}   /           /${NC}
${PC}|     |${SC}//${PC}   /           /${NC}
${PC}|_____|${SC}/${PC}   /___________/${NC}

-------------------------------------

Source: https://github.com/WDaan/VueTorrent
-------------------------------------"
# end of title section

LATEST_RELEASE=$(curl -s -L https://api.github.com/repos/wdaan/vuetorrent/releases/latest \
              | grep "browser_download_url.*zip" \
              | cut -d : -f 2,3 \
              | tr -d \" \
              | xargs) # to trim whitespace

LATEST_RELEASE_VERSION=${LATEST_RELEASE%/*}
LATEST_RELEASE_VERSION=${LATEST_RELEASE_VERSION##*/}

download_vuetorrent () {
  curl -O -J -L $LATEST_RELEASE
}

extract_vuetorrent () {
  unzip vuetorrent.zip -d $1 | awk 'BEGIN {ORS=""; print "Extracting...\n["} {if(NR%2==0)print "."} END {print "]\n"}'
}

if [ ! -d /vuetorrent ]; then
  echo -e "Installing" $LATEST_RELEASE_VERSION"...\n"

  if download_vuetorrent; then
    extract_vuetorrent /

    rm /vuetorrent.zip # Remove zip after unpacking

    echo "Done! VueTorrent is installed in the root folder. Apply it from the WEBUI settings."
  fi
else
  echo -e "Installing" $LATEST_RELEASE_VERSION "using the alternate installer...\n"

  if download_vuetorrent; then
    extract_vuetorrent /temp-vuetorrent

    cp -r /temp-vuetorrent/vuetorrent/* /vuetorrent # mv throws error
    rm -r temp-vuetorrent

    rm vuetorrent.zip # Remove zip after unpacking

    echo "Done! VueTorrent is installed in the root folder."
  fi
fi
